from __future__ import annotations

import tempfile
import unittest
from pathlib import Path
from unittest import mock

from app import main


class DemoTests(unittest.TestCase):
    def test_demo_uses_synthetic_sample_and_real_normalization(self):
        with tempfile.TemporaryDirectory() as directory:
            with mock.patch.object(main, "WORK", Path(directory)):
                result = main.api_demo_run()

            self.assertTrue(result["demo"])
            self.assertTrue(result["synthetic_data"])
            self.assertEqual(result["source_format"], "myheritage")
            self.assertGreater(result["measured_variants"], 0)
            self.assertEqual(result["panel_markers"], 561)
            self.assertFalse(result["imputation_run"])
            self.assertIn("normalized", result["downloads"])
            normalized = Path(directory) / "demo" / "demo_normalized_genotype.txt"
            self.assertTrue(normalized.is_file())
            self.assertIn(
                "# Normalized genotype dataset generated by Genome Normalizer.",
                normalized.read_text(encoding="utf-8"),
            )

    def test_demo_path_allowlist_blocks_upload_endpoints(self):
        self.assertTrue(main.demo_path_allowed("/api/demo-run"))
        self.assertTrue(main.demo_path_allowed("/api/demo-download/panel"))
        self.assertFalse(main.demo_path_allowed("/api/detect"))
        self.assertFalse(main.demo_path_allowed("/api/batch-run"))
        self.assertFalse(main.demo_path_allowed("/api/download/private.txt"))

    def test_test_path_allowlist_only_allows_limited_production_pipeline(self):
        self.assertTrue(main.test_path_allowed("/api/batch-run"))
        self.assertTrue(main.test_path_allowed("/api/batch-progress/job-id"))
        self.assertTrue(main.test_path_allowed("/api/download/result.txt"))
        self.assertFalse(main.test_path_allowed("/api/convert"))
        self.assertFalse(main.test_path_allowed("/api/logs"))


if __name__ == "__main__":
    unittest.main()
