"""
convert.py
==========

Prevod spolocnej internej reprezentacie (GenotypeData) do univerzalneho
23andMe formatu.

23andMe raw data format:
  - textovy, tab-oddeleny
  - komentarova hlavicka zacinajuca '#'
  - stlpce: rsid  chromosome  position  genotype
  - no-call = '--'
  - suradnice = GRCh37 (build 37)
  - genotyp na plus (forward) vlakne referencie
  - alely su orientovane ABECEDNE (napr. 'CT', nikdy 'TC'); niektore ine
    formaty (MyHeritage) toto nerobia, preto konvertor alely defaultne zoradi.
"""

from __future__ import annotations

import datetime as _dt
from typing import Optional

import pandas as pd

from .common import GenotypeData, NO_CALL, chrom_sort_key, normalize_chromosome, sorted_genotype

_DEFAULT_HEADER = """# This data file generated by dna_tools (23andMe-compatible export).
#
# Below is a text version of your DNA data. Fields are TAB-separated.
# Each line corresponds to a single SNP. For each SNP we provide its
# identifier (rsid), its location on the reference human genome, and the
# genotype call (plus/forward strand). Missing/no-call genotypes are '--'.
#
# Reference human assembly build 37 (GRCh37).
# Generated: {generated}
# Source format: {source}
#
# rsid\tchromosome\tposition\tgenotype"""


def to_23andme(data: GenotypeData, drop_no_call: bool = False,
               keep_non_rs: bool = True, sort_alleles: bool = True) -> pd.DataFrame:
    """Pripravi DataFrame v 23andMe rozlozeni (zoradeny podla chrom/pozicie).

    drop_no_call : ak True, vynecha riadky s genotypom '--'.
    keep_non_rs  : ak False, vynecha varianty bez rsID.
    sort_alleles : ak True (default), zoradi alely diploidov abecedne (TC -> CT),
                   aby vystup zodpovedal 23andMe konvencii. Haploidy, indely
                   a no-call ostavaju nedotknute.
    """
    df = data.df.copy()
    df = df[df["position"].notna()].copy()

    if drop_no_call:
        df = df[df["genotype"] != NO_CALL]

    if not keep_non_rs:
        df = df[df["rsid"].astype(str).str.startswith("rs")]

    if sort_alleles:
        df["genotype"] = df["genotype"].map(sorted_genotype)

    df["_ck"] = df["chromosome"].map(chrom_sort_key)
    df = df.sort_values(["_ck", "position"]).drop(columns="_ck").reset_index(drop=True)
    df["position"] = df["position"].astype("Int64")
    return df[["rsid", "chromosome", "position", "genotype"]]


def write_23andme(data: GenotypeData, out_path: str, drop_no_call: bool = False,
                  keep_non_rs: bool = True, sort_alleles: bool = True,
                  header: Optional[str] = None) -> str:
    """Zapise GenotypeData do suboru v 23andMe formate. Vrati cestu k suboru."""
    df = to_23andme(data, drop_no_call=drop_no_call, keep_non_rs=keep_non_rs,
                    sort_alleles=sort_alleles)
    if header is None:
        header = _DEFAULT_HEADER.format(
            generated=_dt.datetime.now().strftime("%a %b %d %H:%M:%S %Y"),
            source=data.source_format,
        )
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(header.rstrip("\n") + "\n")
        for row in df.itertuples(index=False):
            pos = "" if pd.isna(row.position) else int(row.position)
            fh.write("%s\t%s\t%s\t%s\n" % (row.rsid, row.chromosome, pos, row.genotype))
    return out_path


def merge_imputed_into_23andme(sample_path: str, panel_final_path: str,
                               out_path: str, min_conf: float = 0.0) -> dict:
    """Krok 4: nalepi imputovane genotypy na prevedeny 23andMe subor z Kroku 1.

    Zo suboru panel_final.csv (Krok 3) vezme riadky so source='imputed' a:
      - no-call ('--') miesta vo vzorke prepise imputovanou hodnotou,
      - 'absent' pozicie (na 23andMe sablone, chybajuce v MyHeritage) prida,
      - namerane genotypy zo vzorky ostavaju NEDOTKNUTE,
      - min_conf: nepovinny prah max(GP); imputovane pod prahom sa vynechaju.
    Vysledok je kompletny 23andMe .txt. Vrati statistiky.
    """
    from .parsers import parse_file  # lokalny import, aby nevznikol cyklus

    gd = parse_file(sample_path)
    sdf = gd.df.copy()
    sdf["chromosome"] = sdf["chromosome"].map(normalize_chromosome)
    sdf["position"] = pd.to_numeric(sdf["position"], errors="coerce").astype("Int64")

    pf = pd.read_csv(panel_final_path, dtype=str)
    imp = {}
    for r in pf.itertuples(index=False):
        if str(getattr(r, "source", "")) != "imputed":
            continue
        gt = str(r.genotype).strip()
        if gt in ("", NO_CALL, "nan", "None"):
            continue
        conf = getattr(r, "confidence", "")
        try:
            if float(conf) < min_conf:
                continue
        except (TypeError, ValueError):
            if min_conf > 0:
                continue
        try:
            pos = int(float(r.position))
        except (TypeError, ValueError):
            continue
        imp[(normalize_chromosome(str(r.chromosome)), pos)] = (str(r.rsid), sorted_genotype(gt))

    # 1) prepis no-call vo vzorke (namerane nechaj tak)
    replaced = 0
    used = set()
    genos = sdf["genotype"].tolist()
    chroms = sdf["chromosome"].tolist()
    poss = sdf["position"].tolist()
    for i in range(len(sdf)):
        p = poss[i]
        if p is pd.NA:
            continue
        key = (chroms[i], int(p))
        if key in imp:
            used.add(key)
            if genos[i] == NO_CALL:
                genos[i] = imp[key][1]
                replaced += 1
    sdf["genotype"] = genos

    # 2) pridaj absent pozicie ako nove riadky
    extra = [{"rsid": rs, "chromosome": k[0], "position": k[1], "genotype": gt}
             for k, (rs, gt) in imp.items() if k not in used]
    added = len(extra)
    if extra:
        sdf = pd.concat([sdf, pd.DataFrame(extra)], ignore_index=True)

    merged = GenotypeData(sdf[["rsid", "chromosome", "position", "genotype"]],
                          source_format=gd.source_format + "+imputed")
    header = _DEFAULT_HEADER.format(
        generated=_dt.datetime.now().strftime("%a %b %d %H:%M:%S %Y"),
        source=gd.source_format + " + cielena imputacia (Beagle/1000G)",
    )
    write_23andme(merged, out_path, sort_alleles=True, header=header)
    return {
        "total": int(len(merged.df)),
        "replaced_nocall": replaced,
        "added_absent": added,
        "imputed_merged": replaced + added,
    }
